version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-airportdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppassword}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-change_this_secret}
      DATABASE_URL: ${DATABASE_URL:-mysql+pymysql://appuser:apppassword@db:3306/airportdb}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-airportdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppassword}
    ports:
      - "5000:5000"
volumes:
  db_data: